import {IDoxleFont, IDoxleStaticMenuColor} from './DoxleThemeProvider';

export const SERIF_FONT: IDoxleFont = {
  primaryFont: 'IBMPlexSerif-Regular',
  titleFont: 'IBMPlexSerif-Regular',
  subTitleFont: 'IBMPlexSerif-Regular',
  secondaryFont: 'IBMPlexSerif-Regular',
  secondaryTitleFont: 'IBMPlexSerif-Regular',
  serifFont: 'IBMPlexSerif-Regular',
  monoRegular: 'IBMPlexMono-Regular',
  sarinaRegular: 'Sarina-Regular',
  interRegular: 'Inter-Regular',
  sourceCodeRegular: 'SourceCodePro-Regular',
  lexendRegular: 'Lexend-Regular',
};
export const BARLOW_FONT: IDoxleFont = {
  primaryFont: 'BarlowCondensed-Regular',
  titleFont: 'BarlowCondensed-Regular',
  subTitleFont: 'BarlowCondensed-Regular',
  secondaryFont: 'BarlowCondensed-Regular',
  secondaryTitleFont: 'BarlowCondensed-Regular',
  serifFont: 'IBMPlexSerif-Regular',
  monoRegular: 'IBMPlexMono-Regular',
  sarinaRegular: 'Sarina-Regular',
  interRegular: 'Inter-Regular',
  sourceCodeRegular: 'SourceCodePro-Regular',
  lexendRegular: 'Lexend-Regular',
};
export const LEXEND_FONT: IDoxleFont = {
  primaryFont: 'Lexend-Regular',
  titleFont: 'Lexend-Regular',
  subTitleFont: 'Lexend-Regular',
  secondaryFont: 'Lexend-Regular',
  secondaryTitleFont: 'Lexend-Regular',
  serifFont: 'IBMPlexSerif-Regular',
  monoRegular: 'IBMPlexMono-Regular',
  sarinaRegular: 'Sarina-Regular',
  interRegular: 'Inter-Regular',
  sourceCodeRegular: 'SourceCodePro-Regular',
  lexendRegular: 'Lexend-Regular',
};
export const MONO_FONT: IDoxleFont = {
  primaryFont: 'IBMPlexMono-Regular',
  titleFont: 'IBMPlexMono-Regular',
  subTitleFont: 'IBMPlexMono-Regular',
  secondaryFont: 'IBMPlexMono-Regular',
  secondaryTitleFont: 'IBMPlexMono-Regular',
  serifFont: 'IBMPlexSerif-Regular',
  monoRegular: 'IBMPlexMono-Regular',
  sarinaRegular: 'Sarina-Regular',
  interRegular: 'Inter-Regular',
  sourceCodeRegular: 'SourceCodePro-Regular',
  lexendRegular: 'Lexend-Regular',
};
export const DEFAULT_FONT: IDoxleFont = {
  primaryFont: 'BarlowCondensed-Regular',
  titleFont: 'BarlowCondensed-Regular',
  subTitleFont: 'BarlowCondensed-Regular',
  secondaryFont: 'BarlowCondensed-Regular',
  secondaryTitleFont: 'BarlowCondensed-Regular',
  serifFont: 'IBMPlexSerif-Regular',
  monoRegular: 'IBMPlexMono-Regular',
  sarinaRegular: 'Sarina-Regular',
  interRegular: 'Inter-Regular',
  sourceCodeRegular: 'SourceCodePro-Regular',
  lexendRegular: 'Lexend-Regular',
};
export const STATIC_MENU_COLOR: IDoxleStaticMenuColor = {
  staticBg: 'rgba(76,76,84, 1)',
  staticWhiteBg: 'rgba(255,255,255,1)',
  staticWhiteFontColor: 'rgba(255,255,255,1)',
  staticBlackFontColor: 'rgba(0,0,0,1)',
  staticHover: 'rgba(51,51,51,1)',
  staticDivider: 'rgba(169, 200, 242, 0.25)',
  staticBoldDivider: 'rgba(0,0,0,0.1)',
  staticBackdrop: 'rgba(0,0,0,0.7)',
  staticTextFieldBg: 'rgba(55, 55, 61, 1)',
  confirmBtnColor: 'rgba(63, 138, 226, 1)',
  staticDoxleColor: 'rgba(54, 63, 245, 1)',
  staticTbRowHightlight: 'rgba(141, 189, 255, 0.25)',
  canvasBgColor: 'rgba(250,250,252,1)',
  staticBorderColorWhiteBg: 'rgba(230,230,230,1)',
  canvasGridLineColor: 'rgba(230, 230, 230,0.5)',
  canvasSubMenuBg: 'rgba(245, 245, 245, 1)',
};
export const INTER_FONT: IDoxleFont = {
  primaryFont: 'Inter-Regular',
  titleFont: 'Inter-Medium',
  subTitleFont: 'Inter-Regular',
  secondaryFont: 'Inter-Regular',
  secondaryTitleFont: 'Inter-Regular',
  serifFont: 'IBMPlexSerif-Regular',
  monoRegular: 'IBMPlexMono-Regular',
  sarinaRegular: 'Sarina-Regular',
  interRegular: 'Inter-Regular',
  sourceCodeRegular: 'SourceCodePro-Regular',
  lexendRegular: 'Lexend-Regular',
};
